In [1]:
#Imports
import numpy as np
import pandas as pd

#Initial board state
nb_walls = 20
state = np.zeros((17, 17),np.int8)
state[12,8] = 1 #P1
state[10,8] = 2 #P2

#test walls
state[9,8] = 3
state[9,7] = 3
state[9,9] = 3

state[12,9] = 3
state[11,9] = 3
state[10,9] = 3

print(state)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 3 3 3 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 2 3 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 3 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [2]:
def find_legal_moves(player,state):
    
    #Assume all legal moves
    north = True
    south = True
    west = True
    east = True
    
    #Determine player position
    player_pos = np.where(state == player)
    #print('Player Pos: ' + str(player_pos))
    
    #Check if on the sides
    if player_pos[0] == 0:
        #print('On North border')
        north = False
        
    if player_pos[0] == 16:
        #print('On South border')
        south = False
        
    if player_pos[1] == 0:
        #print('On West border')
        west = False
        
    if player_pos[1] == 16:
        #print('On East border')
        east = False
    
    #Determine a wall is near
    wall_near = []
    
    if north:
        if state[int(player_pos[0]) - 1, player_pos[1]] == 3:
            #wall_near.append("North")
            north = False
    if south:
        if state[int(player_pos[0]) + 1, player_pos[1]] == 3:
            #wall_near.append("South")
            south = False
    
    if west:
        if state[int(player_pos[0]), player_pos[1] - 1] == 3:
            #wall_near.append("West")
            west = False
            
    if east:
        if state[int(player_pos[0]), player_pos[1] + 1] == 3:
            #wall_near.append("East")     
            east = False

    #print('There are walls ' + str(wall_near))
    
    #Determine other player position
    if player == 1:
        other_player = 2
    else:
        other_player = 1
    
    other_player_pos = np.where(state == other_player)
    #print('Other player Pos: ' + str(other_player_pos))
    
    
    #Assume no players near
    other_player_north = False
    other_player_south = False
    other_player_west = False
    other_player_east = False   
    
    #Check if near other player
    if (abs(player_pos[0] - other_player_pos[0]) == 2) ^ (abs(player_pos[1] - other_player_pos[1]) == 2):
        #player_near = "undef"
        
        if int(player_pos[0] - other_player_pos[0]) == 2:
            #player_near = "North"
            other_player_north = True
            
        if int(player_pos[0] - other_player_pos[0]) == -2:
            #player_near = "South"
            other_player_south = True

        if int(player_pos[1] - other_player_pos[1]) == 2:
            #player_near = "West"
            other_player_west = True
            
        if int(player_pos[1] - other_player_pos[1]) == -2:
            #player_near = "East"
            other_player_east = True
            
        #print('There is a player to the ' + str(player_near))

    #else:
        #print('There is no player near')
    
    
    #Find legal moves
    legal_moves = []
    
    if north: #If we can go north
        if not other_player_north: #And there is no player to the north
            move = (player_pos[0] - 2, player_pos[1]) #Move 1 space norht
            legal_moves.append(move)
            
        else: #If there is a player to the north
            if not other_player_pos[0] == 0:
                if state[int(player_pos[0]) - 3, player_pos[1]] == 3: #And there is a wall behind them

                    #Check if we can go west or east around the player
                    if not (player_pos[1] == 0) and not (state[int(player_pos[0]) - 2, player_pos[1] - 1] == 3):
                        move = (player_pos[0] - 2, player_pos[1] - 2)
                        legal_moves.append(move)

                    if not (player_pos[1] == 16) and not (state[int(player_pos[0]) - 2, player_pos[1] + 1] == 3):
                        move = (player_pos[0] - 2, player_pos[1] + 2)
                        legal_moves.append(move)

                else: #If there is no wall behind them go over them
                    if not other_player_pos[0] == 0:
                        move = (player_pos[0] - 4, player_pos[1])
                        legal_moves.append(move)

    if south: #If we can go south
        if not other_player_pos[0] == 16:
            if not other_player_south: #And there is no player to the south
                move = (player_pos[0] + 2, player_pos[1]) #Move 1 space south
                legal_moves.append(move)

            else: #If there is a player to the south
                if state[int(player_pos[0]) + 3, player_pos[1]] == 3: #And there is a wall behind them

                    #Check if we can go west or east around the player
                    if not (player_pos[1] == 0) and not (state[int(player_pos[0]) + 2, player_pos[1] - 1] == 3):
                        move = (player_pos[0] + 2, player_pos[1] - 2)
                        legal_moves.append(move)

                    if not (player_pos[1] == 16) and not (state[int(player_pos[0]) + 2, player_pos[1] + 1] == 3):
                        move = (player_pos[0] + 2, player_pos[1] + 2)
                        legal_moves.append(move)

                else: #If there is no wall behind them go over them
                    if not other_player_pos[0] == 16:
                        move = (player_pos[0] + 4, player_pos[1])
                        legal_moves.append(move)

    if west: #If we can go west
        if not other_player_pos[1] == 0:
            if not other_player_west: #And there is no player to the west
                move = (player_pos[0], player_pos[1] - 2) #Move 1 space west
                legal_moves.append(move)

            else: #If there is a player to the west
                if state[int(player_pos[0]), player_pos[1] - 3] == 3: #And there is a wall behind them

                    #Check if we can go north or south around the player
                    if not (player_pos[0] == 0) and not (state[int(player_pos[0]) - 1, player_pos[1] - 2] == 3):
                        move = (player_pos[0] - 2, player_pos[1] - 2)
                        legal_moves.append(move)

                    if not (player_pos[0] == 16) and not (state[int(player_pos[0]) + 1, player_pos[1] - 2] == 3):
                        move = (player_pos[0] + 2, player_pos[1] - 2)
                        legal_moves.append(move)

                else: #If there is no wall behind them and they're not on the border go over them
                    if not other_player_pos[1] == 0:
                        move = (player_pos[0] - 4, player_pos[1])
                        legal_moves.append(move)

    if east: #If we can go west
        if not other_player_pos[1] == 16:
            if not other_player_east: #And there is no player to the east
                move = (player_pos[0], player_pos[1] + 2) #Move 1 space east
                legal_moves.append(move)

            else: #If there is a player to the east
                if state[int(player_pos[0]), player_pos[1] + 3] == 3: #And there is a wall behind them

                    #Check if we can go north or south around the player
                    if not (player_pos[0] == 0) and not (state[int(player_pos[0]) - 1, player_pos[1] + 2] == 3):
                        move = (player_pos[0] - 2, player_pos[1] + 2)
                        legal_moves.append(move)

                    if not (player_pos[0] == 16) and not (state[int(player_pos[0]) + 1, player_pos[1] - 2] == 3):
                        move = (player_pos[0] + 2, player_pos[1] + 2)
                        legal_moves.append(move)

                else: #If there is no wall behind them and they're not on the border go over them
                    if not other_player_pos[1] == 0:
                        move = (player_pos[0] - 4, player_pos[1])
                        legal_moves.append(move)
    return legal_moves

In [3]:
def viz_moves(player,state):
    legal_moves = find_legal_moves(player,state)
    
    viz_state = np.copy(state)
    for move in legal_moves:
        viz_state[int(move[0]),int(move[1])] = 9
    print(viz_state)

def move_player(player,state,move):
    player_pos = np.where(state == player)
    new_state = np.copy(state)
    new_state[int(player_pos[0]),int(player_pos[1])] = 0
    new_state[int(move[0]),int(move[1])] = player
    return new_state

In [4]:
legal_moves = find_legal_moves(1,state)
viz_moves(1,state)
new_state = move_player(1,state,legal_moves[0])

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 3 3 3 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 9 0 2 3 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 9 0 1 3 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 9 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [9]:
#Explore the board
def explore(player,state,iteration,depth):
    
    #Get list of legal moves for this board state
    legal_moves = find_legal_moves(player,state)

    
    #While we are not at the depth
    if iteration <= depth:
        #Iterate over the legal moves
                
        for move in legal_moves:
            #Note the moves
            #state[int(move[0]),int(move[1])] = iteration + 10
            
            #Make the move
            new_state = move_player(player,state,move)
            
            print(new_state)
#             print('Move ' + str(len(legal_moves))
            print('Iteration : ' + str(iteration) + '/' + str(depth))
            #explore the new board after the move
            explore(player,new_state,iteration+1,depth)
            
                  
                  
    #Return the final board state
    #return new_state
        
        
        

In [13]:
print(state)
print('Original State')
explore(1,state,1,5)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 3 3 3 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 2 3 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 3 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
Original State
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 3 3 3 

 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
Iteration : 5/5
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 3 3 3 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 2 3 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
Iteration : 5/5
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 3 3 3 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 2 3 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 3 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
Iteration : 4/5
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 3 3 3

 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
Iteration : 5/5
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 3 3 3 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 2 3 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]]
Iteration : 4/5
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 

 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
Iteration : 5/5
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 3 3 3 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 2 3 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
Iteration : 5/5
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 

 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
Iteration : 5/5
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 3 3 3 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 2 3 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 3 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
Iteration : 5/5
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 

 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
Iteration : 5/5
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 3 3 3 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 2 3 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
Iteration : 5/5
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 

In [15]:
depth = 5
move_matrix = np.zeros((depth,17,17),np.int8)
print(move_matrix)

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]
